#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Manage system config
##?
##? Usage:
##?   config backup
##?   config restore
##?   config reset
docs::parse "$@"

file_path=$DOTFILES_PATH/os/linux/system_config

case $1 in
"backup")
	dconf dump / >$file_path

	echo "Config successfully backed up to $file_path."
	;;
"restore")
	dconf load / <$file_path

	echo "Config successfully restored from $file_path."
	;;
"reset")
	dconf reset -f /

	echo "Config successfully reset."
	;;
*)
	exit 1
	;;
esac
