#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Remove old snaps to free space
##?
##? Usage:
##?   remove_old_snaps
docs::parse "$@"

snap list --all | awk '/disabled/{print $1, $3}' |
  while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done

echo "Old snaps successfully removed!"
